const kingsData = {
    "en": {
        "title": "The Kings of Judah",
        "lang_btn": "עברית",
        "father_label": "Father:",
        "prophet_label": "Major Prophet(s):",
        "button_text": "More Info",
        "kings": [
            { "name": "David", "years_of_reign": "40 years", "father": "Yishai (Jesse)", "major_prophet": "Natan (Nathan), Gad", "image_source": "david.jpg", "wiki_en": "David", "wiki_he": "דוד" },
            { "name": "Shlomo (Solomon)", "years_of_reign": "40 years", "father": "David", "major_prophet": "Achiyah (Ahijah)", "image_source": "shlomo.jpg", "wiki_en": "Solomon", "wiki_he": "שלמה" },
            { "name": "Rehavam (Rehoboam)", "years_of_reign": "17 years", "father": "Shlomo", "major_prophet": "Shemayah (Shemaiah), Ido", "image_source": "rechavam.jpg", "wiki_en": "Rehoboam", "wiki_he": "רחבעם" },
            { "name": "Aviyam (Abijam)", "years_of_reign": "3 years", "father": "Rehavam", "major_prophet": "Ido", "image_source": "Abiyam.jpg", "wiki_en": "Abijam", "wiki_he": "אבים" },
            { "name": "Asa", "years_of_reign": "41 years", "father": "Aviyam", "major_prophet": "Azaryah (Azariah), Chanani (Hanani)", "image_source": "asa.jpg", "wiki_en": "Asa_of_Judah", "wiki_he": "אסא" },
            { "name": "Yehoshafat (Jehoshaphat)", "years_of_reign": "25 years", "father": "Asa", "major_prophet": "Yehu (Jehu), Yachaziel (Jahaziel)", "image_source": "yehoshafat.jpg", "wiki_en": "Jehoshaphat", "wiki_he": "יהושפט" },
            { "name": "Yehoram (Jehoram)", "years_of_reign": "8 years", "father": "Yehoshafat", "major_prophet": "Eliyahu (Elijah)", "image_source": "yehoram.jpg", "wiki_en": "Jehoram_of_Judah", "wiki_he": "יהורם" },
            { "name": "Ahazyahu (Ahaziah)", "years_of_reign": "1 year", "father": "Yehoram", "major_prophet": "Elisha", "image_source": "achazyahu.jpg", "wiki_en": "Ahaziah_of_Judah", "wiki_he": "אחזיהו" },
            { "name": "Atalyah (Athaliah)", "years_of_reign": "6 years", "father": "Ahav (Ahab)", "major_prophet": "Yehoyada (Jehoiada)", "image_source": "atalyah.jpg", "wiki_en": "Athaliah", "wiki_he": "עתליה" },
            { "name": "Yehoash (Joash)", "years_of_reign": "40 years", "father": "Ahazyahu", "major_prophet": "Yehoyada (Jehoiada), Zecharyah (Zechariah)", "image_source": "yehoash.jpg", "wiki_en": "Jehoash_of_Judah", "wiki_he": "יהואש" },
            { "name": "Amatzyah (Amaziah)", "years_of_reign": "29 years", "father": "Yehoash", "major_prophet": "Amotz", "image_source": "amatzyah.jpg", "wiki_en": "Amaziah_of_Judah", "wiki_he": "אמציה" },
            { "name": "Uziyahu (Uzziah)", "years_of_reign": "52 years", "father": "Amatzyah", "major_prophet": "Yeshayahu (Isaiah), Amos", "image_source": "uziyahu.jpg", "wiki_en": "Uzziah", "wiki_he": "עוזיהו" },
            { "name": "Yotam (Jotham)", "years_of_reign": "16 years", "father": "Uziyahu", "major_prophet": "Yeshayahu (Isaiah), Micah (Micah)", "image_source": "yotam.jpg", "wiki_en": "Jotham_of_Judah", "wiki_he": "יותם" },
            { "name": "Ahaz", "years_of_reign": "16 years", "father": "Yotam", "major_prophet": "Yeshayahu (Isaiah), Micah (Micah)", "image_source": "achaz.jpg", "wiki_en": "Ahaz", "wiki_he": "אחז" },
            { "name": "Hizkiyahu (Hezekiah)", "years_of_reign": "29 years", "father": "Ahaz", "major_prophet": "Yeshayahu (Isaiah), Micah (Micah)", "image_source": "chizkiyahu.jpg", "wiki_en": "Hezekiah", "wiki_he": "חזקיהו" },
            { "name": "Menashe (Manasseh)", "years_of_reign": "55 years", "father": "Hizkiyahu", "major_prophet": "Yoel (Joel), Nahum, Havakuk (Habakkuk)", "image_source": "menashe.jpg", "wiki_en": "Manasseh_of_Judah", "wiki_he": "מנשה" },
            { "name": "Amon", "years_of_reign": "2 years", "father": "Menashe", "major_prophet": "Hilikiyahu (Hilkiah)", "image_source": "amon.jpg", "wiki_en": "Amon_of_Judah", "wiki_he": "אמון" },
            { "name": "Yoshiyahu (Josiah)", "years_of_reign": "31 years", "father": "Amon", "major_prophet": "Yirmiyahu (Jeremiah), Tzefanyah (Zephaniah), Chuldah (Huldah)", "image_source": "yoshiyahu.jpg", "wiki_en": "Josiah", "wiki_he": "יאשיהו" },
            { "name": "Yehoahaz (Jehoahaz)", "years_of_reign": "3 months", "father": "Yoshiyahu", "major_prophet": "Yirmiyahu (Jeremiah)", "image_source": "yehoachaz.jpg", "wiki_en": "Jehoahaz_of_Judah", "wiki_he": "יהואחז" },
            { "name": "Yehoyakim (Jehoiakim)", "years_of_reign": "11 years", "father": "Yoshiyahu", "major_prophet": "Yirmiyahu (Jeremiah)", "image_source": "yehoyakim.jpg", "wiki_en": "Jehoiakim", "wiki_he": "יהויקים" },
            { "name": "Yehoyahin (Jehoiachin)", "years_of_reign": "3 months", "father": "Yehoyakim", "major_prophet": "Yirmiyahu (Jeremiah), Yechezkel (Ezekiel)", "image_source": "yehoyachin.jpg", "wiki_en": "Jehoiachin", "wiki_he": "יהויכין" },
            { "name": "Tzidkiyahu (Zedekiah)", "years_of_reign": "11 years", "father": "Yoshiyahu", "major_prophet": "Yirmiyahu (Jeremiah), Yechezkel (Ezekiel)", "image_source": "tzidkiyahu.jpg", "wiki_en": "Zedekiah", "wiki_he": "צדקיהו" }
        ]
    },
    "he": {
        "title": "מלכי יהודה",
        "lang_btn": "English",
        "father_label": "אבא:",
        "prophet_label": "נביא/ים עיקרי/ים:",
        "button_text": "מידע נוסף",
        "kings": [
            { "name": "דוד (David)", "years_of_reign": "40 שנים", "father": "ישי", "major_prophet": "נתן, גד", "image_source": "david.jpg", "wiki_en": "David", "wiki_he": "דוד" },
            { "name": "שלמה (Solomon)", "years_of_reign": "40 שנים", "father": "דוד", "major_prophet": "אחיה השילוני", "image_source": "shlomo.jpg", "wiki_en": "Solomon", "wiki_he": "שלמה" },
            { "name": "רחבעם (Rehoboam)", "years_of_reign": "17 שנים", "father": "שלמה", "major_prophet": "שמעיה, עידו", "image_source": "rechavam.jpg", "wiki_en": "Rehoboam", "wiki_he": "רחבעם" },
            { "name": "אבים (Abijam)", "years_of_reign": "3 שנים", "father": "רחבעם", "major_prophet": "עידו", "image_source": "Abiyam.jpg", "wiki_en": "Abijam", "wiki_he": "אבים" },
            { "name": "אסא (Asa)", "years_of_reign": "41 שנים", "father": "אבים", "major_prophet": "עזריה, חנני", "image_source": "asa.jpg", "wiki_en": "Asa_of_Judah", "wiki_he": "אסא" },
            { "name": "יהושפט (Jehoshaphat)", "years_of_reign": "25 שנים", "father": "אסא", "major_prophet": "יהוא, יחזיאל", "image_source": "yehoshafat.jpg", "wiki_en": "Jehoshaphat", "wiki_he": "יהושפט" },
            { "name": "יהורם (Jehoram)", "years_of_reign": "8 שנים", "father": "יהושפט", "major_prophet": "אליהו", "image_source": "yehoram.jpg", "wiki_en": "Jehoram_of_Judah", "wiki_he": "יהורם" },
            { "name": "אחזיהו (Ahaziah)", "years_of_reign": "שנה אחת", "father": "יהורם", "major_prophet": "אלישע", "image_source": "achazyahu.jpg", "wiki_en": "Ahaziah_of_Judah", "wiki_he": "אחזיהו" },
            { "name": "עתליה (Athaliah)", "years_of_reign": "6 שנים", "father": "אחאב", "major_prophet": "יהוידע", "image_source": "atalyah.jpg", "wiki_en": "Athaliah", "wiki_he": "עתליה" },
            { "name": "יהואש (Joash)", "years_of_reign": "40 שנים", "father": "אחזיהו", "major_prophet": "יהוידע, זכריה", "image_source": "yehoash.jpg", "wiki_en": "Jehoash_of_Judah", "wiki_he": "יהואש" },
            { "name": "אמציה (Amaziah)", "years_of_reign": "29 שנים", "father": "יהואש", "major_prophet": "אמוץ", "image_source": "amatzyah.jpg", "wiki_en": "Amaziah_of_Judah", "wiki_he": "אמציה" },
            { "name": "עוזיהו (Uzziah)", "years_of_reign": "52 שנים", "father": "אמציה", "major_prophet": "ישעיהו, עמוס", "image_source": "uziyahu.jpg", "wiki_en": "Uzziah", "wiki_he": "עוזיהו" },
            { "name": "יותם (Jotham)", "years_of_reign": "16 שנים", "father": "עוזיהו", "major_prophet": "ישעיהו, מיכה", "image_source": "yotam.jpg", "wiki_en": "Jotham_of_Judah", "wiki_he": "יותם" },
            { "name": "אחז (Ahaz)", "years_of_reign": "16 שנים", "father": "יותם", "major_prophet": "ישעיהו, מיכה", "image_source": "achaz.jpg", "wiki_en": "Ahaz", "wiki_he": "אחז" },
            { "name": "חזקיהו (Hezekiah)", "years_of_reign": "29 שנים", "father": "אחז", "major_prophet": "ישעיהו, מיכה", "image_source": "chizkiyahu.jpg", "wiki_en": "Hezekiah", "wiki_he": "חזקיהו" },
            { "name": "מנשה (Manasseh)", "years_of_reign": "55 שנים", "father": "חזקיהו", "major_prophet": "יואל, נחום, חבקוק", "image_source": "menashe.jpg", "wiki_en": "Manasseh_of_Judah", "wiki_he": "מנשה" },
            { "name": "אמון (Amon)", "years_of_reign": "שנתיים", "father": "מנשה", "major_prophet": "חלקיהו", "image_source": "amon.jpg", "wiki_en": "Amon_of_Judah", "wiki_he": "אמון" },
            { "name": "יאשיהו (Josiah)", "years_of_reign": "31 שנים", "father": "אמון", "major_prophet": "ירמיהו, צפניה, חולדה", "image_source": "yoshiyahu.jpg", "wiki_en": "Josiah", "wiki_he": "יאשיהו" },
            { "name": "יהואחז (Jehoahaz)", "years_of_reign": "3 חודשים", "father": "יאשיהו", "major_prophet": "ירמיהו", "image_source": "yehoachaz.jpg", "wiki_en": "Jehoahaz_of_Judah", "wiki_he": "יהואחז" },
            { "name": "יהויקים (Jehoiakim)", "years_of_reign": "11 שנים", "father": "יאשיהו", "major_prophet": "ירמיהו", "image_source": "yehoyakim.jpg", "wiki_en": "Jehoiakim", "wiki_he": "יהויקים" },
            { "name": "יהויכין (Jehoiachin)", "years_of_reign": "3 חודשים", "father": "יהויקים", "major_prophet": "ירמיהו, יחזקאל", "image_source": "yehoyachin.jpg", "wiki_en": "Jehoiachin", "wiki_he": "יהויכין" },
            { "name": "צדקיהו (Zedekiah)", "years_of_reign": "11 שנים", "father": "יאשיהו", "major_prophet": "ירמיהו, יחזקאל", "image_source": "tzidkiyahu.jpg", "wiki_en": "Zedekiah", "wiki_he": "צדקיהו" }
        ]
    }
};